# Generated by Django 3.1.7 on 2021-09-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210910_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
