# Generated by Django 3.2.7 on 2021-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210910_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='a', upload_to='images/'),
        ),
    ]
